CREATE DATABASE CALLCENTER 
GO
USE CALLCENTER
GO
CREATE TABLE TipoIncidencia(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Descripcion VARCHAR(100) NOT NULL
)
GO
CREATE TABLE PrioridadIncidencia(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Descripcion VARCHAR(100) NOT NULL
)
GO
CREATE TABLE EstadoIncidencia(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Descripcion VARCHAR(100) NOT NULL
)
GO
CREATE TABLE Telefonista(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Legajo INT NOT NULL UNIQUE
)
GO
CREATE TABLE Cliente(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE Incidente(
	ID INT PRIMARY KEY IDENTITY (1,1),
	IdTipoIncidencia INT NOT NULL FOREIGN KEY REFERENCES TipoIncidencia (ID),
	IdPrioridad INT NOT NULL FOREIGN KEY REFERENCES PrioridadIncidencia (ID),
	Problematica TEXT NULL,
	IdEstado INT NOT NULL FOREIGN KEY REFERENCES EstadoIncidencia (ID),
	IdCliente INT NOT NULL FOREIGN KEY REFERENCES Cliente (ID),
	Resolucion TEXT NULL,
	IdTelefonista INT NOT NULL FOREIGN KEY REFERENCES Telefonista (ID),
	Motivo VARCHAR(250) NULL
)
GO