CREATE DATABASE CALLCENTER 
GO
USE CALLCENTER
GO
CREATE TABLE TipoIncidencia(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Descripcion VARCHAR(100) NOT NULL
)
GO
CREATE TABLE PrioridadIncidencia(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Descripcion VARCHAR(100) NOT NULL
)
GO
CREATE TABLE EstadoIncidencia(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Descripcion VARCHAR(100) NOT NULL
)
GO
CREATE TABLE Cliente(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE Perfil(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Descripcion VARCHAR(100) NOT NULL
)
GO
CREATE TABLE Usuario(
	ID INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	DNI VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	IdPerfil INT NOT NULL FOREIGN KEY REFERENCES Perfil (ID),
)
GO
CREATE TABLE Incidente(
	ID INT PRIMARY KEY IDENTITY (1,1),
	IdTipoIncidencia INT NOT NULL FOREIGN KEY REFERENCES TipoIncidencia (ID),
	IdPrioridad INT NOT NULL FOREIGN KEY REFERENCES PrioridadIncidencia (ID),
	Problematica TEXT NULL,
	IdEstado INT NOT NULL FOREIGN KEY REFERENCES EstadoIncidencia (ID),
	IdCliente INT NOT NULL FOREIGN KEY REFERENCES Cliente (ID),
	Resolucion TEXT NULL,
	IdUsuario INT NOT NULL FOREIGN KEY REFERENCES Usuario (ID),
	Motivo VARCHAR(250) NULL
)
GO
